### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by hexruin** [developer60-stack/v4#7]
Salut, Tester de arhive imi poti spune. Am gasit un bug la arhiva si mai exact la fisierul "bios.txt"!
Cum sta treaba? Pai daca este un spatiu liber in bios.txt gen:  https://prnt.sc/wf99wc , il vede ca ip: https://prnt.sc/wf9aoz, si din cauza asta se produce un bug, brute ul nu se mai opreste, nu mai primeste pkill.
Ideea este ca trebuie facut ceva in arhiva sa nu citeasca spatiile libere si simbolurile.

Discord: DodeL™#7948

**Comment by RedHat-Pychol** [comment]
Rezolvat. În următorul update nu o sa mai fie problema.
